[general]
import = ["rose-pine-dawn.toml"]

[window]
dimensions = { columns = 131, lines = 53 }
position = { x = 475, y = 100 }
decorations = "Buttonless"
option_as_alt = "OnlyLeft"

[scrolling]
history = 100000

[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Light" }
italic = { family = "JetBrainsMonoNL Nerd Font Mono", style = "LightItalic" }
bold = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font Mono", style = "LightItalic" }
size = 15.5

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 600
[keyboard]
bindings = [
  { key = "Return", mods = "Shift", chars = "\n" }
]
