[general]
import = ["rose-pine-dawn.toml"]

[window]
dimensions = { columns = 131, lines = 53 }
position = { x = 475, y = 100 }
decorations = "Buttonless"
option_as_alt = "OnlyLeft"

[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Light" }
italic = { family = "JetBrainsMonoNL Nerd Font Mono", style = "LightItalic" }
bold = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font Mono", style = "LightItalic" }
size = 15.5

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 600

[keyboard]
#bindings = [
#  #{ key = "X", mods = "Control", chars = "\u001b[88;4u" },
#  { key = "X", mods = "Control|Shift", chars = "\u001b[88;5u" },
#  { key = "Return",  mods = "Shift",  chars = "\u001b[13;3u" },
#  { key = "Return",  mods = "Control",  chars = "\u001b[13;5u" },
#  { key = "Return",  mods = "Alt",  chars = "\u001b[13;2u" },
#  { key = "Return",  mods = "Control|Shift",  chars = "\u001b[13;6u" },
#  { key = "Space",   mods = "Shift",  chars = "\u001b[32;3u" },
#  #{ key = "Space",   mods = "Control",  chars = "\u001b[32;1u" },
#  { key = "Space",   mods = "Alt",  chars = "\u001b[32;2u" },
#  #{ key = "Space",   mods = "Control|Shift",  chars = "\u001b[32;6u" },
#]
