[tools]
bun = "1"
gemini-cli = "latest"
"github:can1357/oh-my-pi" = "latest"
go = "1.25"
lua = "5.1.5"
neovim = "latest"
ni = "latest"
node = "lts"
"npm:@mariozechner/pi-coding-agent" = "latest"
opencode = "latest"
pnpm = "10"
python = "latest"
yarn = "1"
